[package]
name = "xassembler"
version = "0.1.0"
authors = ["adam-mcdaniel <adam.mcdanie17@gmail.com>"]
edition = "2018"

[[bin]]
name = "xassembler"
path = "src/bin.rs"

[dependencies]
honeycomb = "0.1.4"